#!/bin/bash
# This Script will make the example Sketch and will Upload it to the Bebop drone

#Define Parameters
FILE='AP_OpticalFlow_test'
NAME='flow'
BUILD_PATH='/home/lumeier/bebop/ardupilot/build/bebop/examples/'



#Compile for bebop and strip binaries
#alias waf="$PWD/modules/waf/waf-light"
#waf configure --board=bebop
#waf examples -j8

#Connect via ftp and upload file
adb connect 192.168.43.1:9050
sleep 1
adb shell mount -o remount,rw /
sleep 1
cp $BUILD_PATH$FILE $BUILD_PATH$NAME
sleep 1
adb push $BUILD_PATH$NAME /usr/bin/
sleep 1
adb shell $NAME
sleep 100
usr
